language: cpp
dist: trusty

env:
  - VERSION=3.8
  - VERSION=3.9
  - VERSION=4.0

before_install:
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main"
  - sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
  - sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main"
  - sudo apt-get update
  - sudo apt-get install -y llvm-$VERSION-dev
script:
  - echo $PATH
  - ls -l /usr/share
  - ls -l /usr/lib/llvm-$VERSION
  - cmake -P test-llvm-package.cmake -DTEST_LLVM_VERSION=$VERSION -DCMAKE_PREFIX_PATH="/usr:/usr/lib/llvm-$VERSION/share"
