language: cpp
dist: trusty
services:
  - docker

env:
  - VERSION=3.8 SYSTEM=xenial
  - VERSION=3.8 SYSTEM=jessie
  - VERSION=3.9 SYSTEM=xenial
  - VERSION=4.0 SYSTEM=xenial

script:
  - source configure.sh
  - CONTAINER=`docker run -d $IMAGE tail -f /dev/null`
  - docker exec $CONTAINER cat /etc/issue
  - docker exec $CONTAINER sh -c "echo '$REPO' >> /etc/apt/sources.list"
  - docker exec $CONTAINER cat /etc/apt/sources.list
  - docker exec $CONTAINER apt-get -q update
  - docker exec $CONTAINER apt-get -q install -y --allow-unauthenticated cmake llvm-$VERSION-dev

  - docker cp test-llvm-package.cmake $CONTAINER:/test-llvm-package.cmake

  - docker exec $CONTAINER dpkg-query -L llvm-$VERSION-dev
  - docker exec $CONTAINER cmake -P test-llvm-package.cmake

  - docker kill $CONTAINER
